# Generated by Django 5.2.6 on 2025-09-04 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('materials', models.TextField(blank=True, null=True)),
                ('number_of_players', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=50)),
                ('video_link', models.URLField(blank=True, null=True)),
                ('folders', models.ManyToManyField(related_name='games', to='Games.folder')),
            ],
        ),
    ]
